/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_threebit_jvr_GC_0005fPARM_0005fBLK */

#ifndef _Included_net_threebit_jvr_GC_0005fPARM_0005fBLK
#define _Included_net_threebit_jvr_GC_0005fPARM_0005fBLK
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: logger */
/* Inaccessible static: class_00024net_00024threebit_00024jvr_00024GC_PARM_BLK */
/*
 * Class:     net_threebit_jvr_GC_0005fPARM_0005fBLK
 * Method:    allocateNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_threebit_jvr_GC_1PARM_1BLK_allocateNative
  (JNIEnv *, jobject);

/*
 * Class:     net_threebit_jvr_GC_0005fPARM_0005fBLK
 * Method:    releaseNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_threebit_jvr_GC_1PARM_1BLK_releaseNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
