/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_threebit_jvr_DX_0005fXPB */

#ifndef _Included_net_threebit_jvr_DX_0005fXPB
#define _Included_net_threebit_jvr_DX_0005fXPB
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: logger */
/* Inaccessible static: class_00024net_00024threebit_00024jvr_00024DX_XPB */
/*
 * Class:     net_threebit_jvr_DX_0005fXPB
 * Method:    allocate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_threebit_jvr_DX_1XPB_allocate
  (JNIEnv *, jobject);

/*
 * Class:     net_threebit_jvr_DX_0005fXPB
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_threebit_jvr_DX_1XPB_release
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
