/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_threebit_jvr_DV_0005fDIGIT */

#ifndef _Included_net_threebit_jvr_DV_0005fDIGIT
#define _Included_net_threebit_jvr_DV_0005fDIGIT
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: logger */
/* Inaccessible static: lock */
/* Inaccessible static: class_00024net_00024threebit_00024jvr_00024DV_DIGIT */
/*
 * Class:     net_threebit_jvr_DV_0005fDIGIT
 * Method:    allocateBuffer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_threebit_jvr_DV_1DIGIT_allocateBuffer
  (JNIEnv *, jclass);

/*
 * Class:     net_threebit_jvr_DV_0005fDIGIT
 * Method:    releaseBuffer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_threebit_jvr_DV_1DIGIT_releaseBuffer
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_threebit_jvr_DV_0005fDIGIT
 * Method:    getDigits
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_threebit_jvr_DV_1DIGIT_getDigits
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
